//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.3928.0 自動產生。
// 
namespace ModelCore.Schema.TurnKey.Allowance {
    using System.Globalization;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    public partial class CancelAllowanceConfirm {
        
        /// <remarks/>
        public string CancelAllowanceNumber;

        /// <remarks/>
        public AllowanceTypeEnum AllowanceType = AllowanceTypeEnum.Item2;

        /// <remarks/>
        public string AllowanceDate;
        
        /// <remarks/>
        public string BuyerId;
        
        /// <remarks/>
        public string SellerId;

        [XmlIgnore]
        public DateTime CancelDateTime { get; set; }

        /// <remarks/>
        public string CancelDate
        {
            get => CancelDateTime.ToString("yyyyMMdd");
            set => CancelDateTime = DateTime.ParseExact(value, "yyyyMMdd", CultureInfo.InvariantCulture).Add(CancelDateTime.TimeOfDay);
        }

        /// <remarks/>
        public string CancelTime
        {
            get => CancelDateTime.ToString("HH:mm:ss");
            set => CancelDateTime = CancelDateTime.Date.Add(TimeSpan.Parse(value));
        }
        /// <remarks/>
        public string Remark;
    }
}
