//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCore.EV8DSMS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelCore.EV8DSMS.SMSSoap")]
    public interface SMSSoap
    {
        
        // CODEGEN: Generating message contract since element name userID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConnection", ReplyAction="*")]
        ModelCore.EV8DSMS.getConnectionResponse getConnection(ModelCore.EV8DSMS.getConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getConnectionResponse> getConnectionAsync(ModelCore.EV8DSMS.getConnectionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeConnection", ReplyAction="*")]
        ModelCore.EV8DSMS.closeConnectionResponse closeConnection(ModelCore.EV8DSMS.closeConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.closeConnectionResponse> closeConnectionAsync(ModelCore.EV8DSMS.closeConnectionRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMS", ReplyAction="*")]
        ModelCore.EV8DSMS.sendSMSResponse sendSMS(ModelCore.EV8DSMS.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendSMSResponse> sendSMSAsync(ModelCore.EV8DSMS.sendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMessage", ReplyAction="*")]
        ModelCore.EV8DSMS.sendMessageResponse sendMessage(ModelCore.EV8DSMS.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendMessageResponse> sendMessageAsync(ModelCore.EV8DSMS.sendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendParamSMS", ReplyAction="*")]
        ModelCore.EV8DSMS.sendParamSMSResponse sendParamSMS(ModelCore.EV8DSMS.sendParamSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendParamSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendParamSMSResponse> sendParamSMSAsync(ModelCore.EV8DSMS.sendParamSMSRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eraseBooking", ReplyAction="*")]
        ModelCore.EV8DSMS.eraseBookingResponse eraseBooking(ModelCore.EV8DSMS.eraseBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eraseBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.eraseBookingResponse> eraseBookingAsync(ModelCore.EV8DSMS.eraseBookingRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryStatus", ReplyAction="*")]
        ModelCore.EV8DSMS.getDeliveryStatusResponse getDeliveryStatus(ModelCore.EV8DSMS.getDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getDeliveryStatusResponse> getDeliveryStatusAsync(ModelCore.EV8DSMS.getDeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCredit", ReplyAction="*")]
        ModelCore.EV8DSMS.getCreditResponse getCredit(ModelCore.EV8DSMS.getCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getCreditResponse> getCreditAsync(ModelCore.EV8DSMS.getCreditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getConnectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getConnection", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getConnectionRequestBody Body;
        
        public getConnectionRequest()
        {
        }
        
        public getConnectionRequest(ModelCore.EV8DSMS.getConnectionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getConnectionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getConnectionRequestBody()
        {
        }
        
        public getConnectionRequestBody(string userID, string password)
        {
            this.userID = userID;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getConnectionResponseBody Body;
        
        public getConnectionResponse()
        {
        }
        
        public getConnectionResponse(ModelCore.EV8DSMS.getConnectionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getConnectionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getConnectionResult;
        
        public getConnectionResponseBody()
        {
        }
        
        public getConnectionResponseBody(string getConnectionResult)
        {
            this.getConnectionResult = getConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnection", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.closeConnectionRequestBody Body;
        
        public closeConnectionRequest()
        {
        }
        
        public closeConnectionRequest(ModelCore.EV8DSMS.closeConnectionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeConnectionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        public closeConnectionRequestBody()
        {
        }
        
        public closeConnectionRequestBody(string sessionKey)
        {
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.closeConnectionResponseBody Body;
        
        public closeConnectionResponse()
        {
        }
        
        public closeConnectionResponse(ModelCore.EV8DSMS.closeConnectionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeConnectionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string closeConnectionResult;
        
        public closeConnectionResponseBody()
        {
        }
        
        public closeConnectionResponseBody(string closeConnectionResult)
        {
            this.closeConnectionResult = closeConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendSMSRequestBody Body;
        
        public sendSMSRequest()
        {
        }
        
        public sendSMSRequest(ModelCore.EV8DSMS.sendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sendTime;
        
        public sendSMSRequestBody()
        {
        }
        
        public sendSMSRequestBody(string sessionKey, string subject, string content, string mobile, string sendTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.content = content;
            this.mobile = mobile;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendSMSResponseBody Body;
        
        public sendSMSResponse()
        {
        }
        
        public sendSMSResponse(ModelCore.EV8DSMS.sendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendSMSResult;
        
        public sendSMSResponseBody()
        {
        }
        
        public sendSMSResponseBody(string sendSMSResult)
        {
            this.sendSMSResult = sendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendMessageRequestBody Body;
        
        public sendMessageRequest()
        {
        }
        
        public sendMessageRequest(ModelCore.EV8DSMS.sendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sendTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string retryTime;
        
        public sendMessageRequestBody()
        {
        }
        
        public sendMessageRequestBody(string sessionKey, string subject, string content, string mobile, string sendTime, string retryTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.content = content;
            this.mobile = mobile;
            this.sendTime = sendTime;
            this.retryTime = retryTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendMessageResponseBody Body;
        
        public sendMessageResponse()
        {
        }
        
        public sendMessageResponse(ModelCore.EV8DSMS.sendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMessageResult;
        
        public sendMessageResponseBody()
        {
        }
        
        public sendMessageResponseBody(string sendMessageResult)
        {
            this.sendMessageResult = sendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendParamSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendParamSMS", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendParamSMSRequestBody Body;
        
        public sendParamSMSRequest()
        {
        }
        
        public sendParamSMSRequest(ModelCore.EV8DSMS.sendParamSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendParamSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contentXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sendTime;
        
        public sendParamSMSRequestBody()
        {
        }
        
        public sendParamSMSRequestBody(string sessionKey, string subject, string contentXML, string sendTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.contentXML = contentXML;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendParamSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendParamSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.sendParamSMSResponseBody Body;
        
        public sendParamSMSResponse()
        {
        }
        
        public sendParamSMSResponse(ModelCore.EV8DSMS.sendParamSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendParamSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendParamSMSResult;
        
        public sendParamSMSResponseBody()
        {
        }
        
        public sendParamSMSResponseBody(string sendParamSMSResult)
        {
            this.sendParamSMSResult = sendParamSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eraseBookingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eraseBooking", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.eraseBookingRequestBody Body;
        
        public eraseBookingRequest()
        {
        }
        
        public eraseBookingRequest(ModelCore.EV8DSMS.eraseBookingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eraseBookingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string batchID;
        
        public eraseBookingRequestBody()
        {
        }
        
        public eraseBookingRequestBody(string sessionKey, string batchID)
        {
            this.sessionKey = sessionKey;
            this.batchID = batchID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eraseBookingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eraseBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.eraseBookingResponseBody Body;
        
        public eraseBookingResponse()
        {
        }
        
        public eraseBookingResponse(ModelCore.EV8DSMS.eraseBookingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eraseBookingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eraseBookingResult;
        
        public eraseBookingResponseBody()
        {
        }
        
        public eraseBookingResponseBody(string eraseBookingResult)
        {
            this.eraseBookingResult = eraseBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryStatus", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getDeliveryStatusRequestBody Body;
        
        public getDeliveryStatusRequest()
        {
        }
        
        public getDeliveryStatusRequest(ModelCore.EV8DSMS.getDeliveryStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string batchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageNo;
        
        public getDeliveryStatusRequestBody()
        {
        }
        
        public getDeliveryStatusRequestBody(string sessionKey, string batchID, string pageNo)
        {
            this.sessionKey = sessionKey;
            this.batchID = batchID;
            this.pageNo = pageNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getDeliveryStatusResponseBody Body;
        
        public getDeliveryStatusResponse()
        {
        }
        
        public getDeliveryStatusResponse(ModelCore.EV8DSMS.getDeliveryStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeliveryStatusResult;
        
        public getDeliveryStatusResponseBody()
        {
        }
        
        public getDeliveryStatusResponseBody(string getDeliveryStatusResult)
        {
            this.getDeliveryStatusResult = getDeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCredit", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getCreditRequestBody Body;
        
        public getCreditRequest()
        {
        }
        
        public getCreditRequest(ModelCore.EV8DSMS.getCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        public getCreditRequestBody()
        {
        }
        
        public getCreditRequestBody(string sessionKey)
        {
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelCore.EV8DSMS.getCreditResponseBody Body;
        
        public getCreditResponse()
        {
        }
        
        public getCreditResponse(ModelCore.EV8DSMS.getCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCreditResult;
        
        public getCreditResponseBody()
        {
        }
        
        public getCreditResponseBody(string getCreditResult)
        {
            this.getCreditResult = getCreditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SMSSoapChannel : ModelCore.EV8DSMS.SMSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<ModelCore.EV8DSMS.SMSSoap>, ModelCore.EV8DSMS.SMSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), SMSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.getConnectionResponse ModelCore.EV8DSMS.SMSSoap.getConnection(ModelCore.EV8DSMS.getConnectionRequest request)
        {
            return base.Channel.getConnection(request);
        }
        
        public string getConnection(string userID, string password)
        {
            ModelCore.EV8DSMS.getConnectionRequest inValue = new ModelCore.EV8DSMS.getConnectionRequest();
            inValue.Body = new ModelCore.EV8DSMS.getConnectionRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.password = password;
            ModelCore.EV8DSMS.getConnectionResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).getConnection(inValue);
            return retVal.Body.getConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getConnectionResponse> ModelCore.EV8DSMS.SMSSoap.getConnectionAsync(ModelCore.EV8DSMS.getConnectionRequest request)
        {
            return base.Channel.getConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.getConnectionResponse> getConnectionAsync(string userID, string password)
        {
            ModelCore.EV8DSMS.getConnectionRequest inValue = new ModelCore.EV8DSMS.getConnectionRequest();
            inValue.Body = new ModelCore.EV8DSMS.getConnectionRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.password = password;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).getConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.closeConnectionResponse ModelCore.EV8DSMS.SMSSoap.closeConnection(ModelCore.EV8DSMS.closeConnectionRequest request)
        {
            return base.Channel.closeConnection(request);
        }
        
        public string closeConnection(string sessionKey)
        {
            ModelCore.EV8DSMS.closeConnectionRequest inValue = new ModelCore.EV8DSMS.closeConnectionRequest();
            inValue.Body = new ModelCore.EV8DSMS.closeConnectionRequestBody();
            inValue.Body.sessionKey = sessionKey;
            ModelCore.EV8DSMS.closeConnectionResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).closeConnection(inValue);
            return retVal.Body.closeConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.closeConnectionResponse> ModelCore.EV8DSMS.SMSSoap.closeConnectionAsync(ModelCore.EV8DSMS.closeConnectionRequest request)
        {
            return base.Channel.closeConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.closeConnectionResponse> closeConnectionAsync(string sessionKey)
        {
            ModelCore.EV8DSMS.closeConnectionRequest inValue = new ModelCore.EV8DSMS.closeConnectionRequest();
            inValue.Body = new ModelCore.EV8DSMS.closeConnectionRequestBody();
            inValue.Body.sessionKey = sessionKey;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).closeConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.sendSMSResponse ModelCore.EV8DSMS.SMSSoap.sendSMS(ModelCore.EV8DSMS.sendSMSRequest request)
        {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string sessionKey, string subject, string content, string mobile, string sendTime)
        {
            ModelCore.EV8DSMS.sendSMSRequest inValue = new ModelCore.EV8DSMS.sendSMSRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            ModelCore.EV8DSMS.sendSMSResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).sendSMS(inValue);
            return retVal.Body.sendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendSMSResponse> ModelCore.EV8DSMS.SMSSoap.sendSMSAsync(ModelCore.EV8DSMS.sendSMSRequest request)
        {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendSMSResponse> sendSMSAsync(string sessionKey, string subject, string content, string mobile, string sendTime)
        {
            ModelCore.EV8DSMS.sendSMSRequest inValue = new ModelCore.EV8DSMS.sendSMSRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.sendMessageResponse ModelCore.EV8DSMS.SMSSoap.sendMessage(ModelCore.EV8DSMS.sendMessageRequest request)
        {
            return base.Channel.sendMessage(request);
        }
        
        public string sendMessage(string sessionKey, string subject, string content, string mobile, string sendTime, string retryTime)
        {
            ModelCore.EV8DSMS.sendMessageRequest inValue = new ModelCore.EV8DSMS.sendMessageRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendMessageRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            inValue.Body.retryTime = retryTime;
            ModelCore.EV8DSMS.sendMessageResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendMessageResponse> ModelCore.EV8DSMS.SMSSoap.sendMessageAsync(ModelCore.EV8DSMS.sendMessageRequest request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendMessageResponse> sendMessageAsync(string sessionKey, string subject, string content, string mobile, string sendTime, string retryTime)
        {
            ModelCore.EV8DSMS.sendMessageRequest inValue = new ModelCore.EV8DSMS.sendMessageRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendMessageRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            inValue.Body.retryTime = retryTime;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.sendParamSMSResponse ModelCore.EV8DSMS.SMSSoap.sendParamSMS(ModelCore.EV8DSMS.sendParamSMSRequest request)
        {
            return base.Channel.sendParamSMS(request);
        }
        
        public string sendParamSMS(string sessionKey, string subject, string contentXML, string sendTime)
        {
            ModelCore.EV8DSMS.sendParamSMSRequest inValue = new ModelCore.EV8DSMS.sendParamSMSRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendParamSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.contentXML = contentXML;
            inValue.Body.sendTime = sendTime;
            ModelCore.EV8DSMS.sendParamSMSResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).sendParamSMS(inValue);
            return retVal.Body.sendParamSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendParamSMSResponse> ModelCore.EV8DSMS.SMSSoap.sendParamSMSAsync(ModelCore.EV8DSMS.sendParamSMSRequest request)
        {
            return base.Channel.sendParamSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.sendParamSMSResponse> sendParamSMSAsync(string sessionKey, string subject, string contentXML, string sendTime)
        {
            ModelCore.EV8DSMS.sendParamSMSRequest inValue = new ModelCore.EV8DSMS.sendParamSMSRequest();
            inValue.Body = new ModelCore.EV8DSMS.sendParamSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.contentXML = contentXML;
            inValue.Body.sendTime = sendTime;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).sendParamSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.eraseBookingResponse ModelCore.EV8DSMS.SMSSoap.eraseBooking(ModelCore.EV8DSMS.eraseBookingRequest request)
        {
            return base.Channel.eraseBooking(request);
        }
        
        public string eraseBooking(string sessionKey, string batchID)
        {
            ModelCore.EV8DSMS.eraseBookingRequest inValue = new ModelCore.EV8DSMS.eraseBookingRequest();
            inValue.Body = new ModelCore.EV8DSMS.eraseBookingRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            ModelCore.EV8DSMS.eraseBookingResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).eraseBooking(inValue);
            return retVal.Body.eraseBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.eraseBookingResponse> ModelCore.EV8DSMS.SMSSoap.eraseBookingAsync(ModelCore.EV8DSMS.eraseBookingRequest request)
        {
            return base.Channel.eraseBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.eraseBookingResponse> eraseBookingAsync(string sessionKey, string batchID)
        {
            ModelCore.EV8DSMS.eraseBookingRequest inValue = new ModelCore.EV8DSMS.eraseBookingRequest();
            inValue.Body = new ModelCore.EV8DSMS.eraseBookingRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).eraseBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.getDeliveryStatusResponse ModelCore.EV8DSMS.SMSSoap.getDeliveryStatus(ModelCore.EV8DSMS.getDeliveryStatusRequest request)
        {
            return base.Channel.getDeliveryStatus(request);
        }
        
        public string getDeliveryStatus(string sessionKey, string batchID, string pageNo)
        {
            ModelCore.EV8DSMS.getDeliveryStatusRequest inValue = new ModelCore.EV8DSMS.getDeliveryStatusRequest();
            inValue.Body = new ModelCore.EV8DSMS.getDeliveryStatusRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            inValue.Body.pageNo = pageNo;
            ModelCore.EV8DSMS.getDeliveryStatusResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).getDeliveryStatus(inValue);
            return retVal.Body.getDeliveryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getDeliveryStatusResponse> ModelCore.EV8DSMS.SMSSoap.getDeliveryStatusAsync(ModelCore.EV8DSMS.getDeliveryStatusRequest request)
        {
            return base.Channel.getDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.getDeliveryStatusResponse> getDeliveryStatusAsync(string sessionKey, string batchID, string pageNo)
        {
            ModelCore.EV8DSMS.getDeliveryStatusRequest inValue = new ModelCore.EV8DSMS.getDeliveryStatusRequest();
            inValue.Body = new ModelCore.EV8DSMS.getDeliveryStatusRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            inValue.Body.pageNo = pageNo;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).getDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelCore.EV8DSMS.getCreditResponse ModelCore.EV8DSMS.SMSSoap.getCredit(ModelCore.EV8DSMS.getCreditRequest request)
        {
            return base.Channel.getCredit(request);
        }
        
        public string getCredit(string sessionKey)
        {
            ModelCore.EV8DSMS.getCreditRequest inValue = new ModelCore.EV8DSMS.getCreditRequest();
            inValue.Body = new ModelCore.EV8DSMS.getCreditRequestBody();
            inValue.Body.sessionKey = sessionKey;
            ModelCore.EV8DSMS.getCreditResponse retVal = ((ModelCore.EV8DSMS.SMSSoap)(this)).getCredit(inValue);
            return retVal.Body.getCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelCore.EV8DSMS.getCreditResponse> ModelCore.EV8DSMS.SMSSoap.getCreditAsync(ModelCore.EV8DSMS.getCreditRequest request)
        {
            return base.Channel.getCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelCore.EV8DSMS.getCreditResponse> getCreditAsync(string sessionKey)
        {
            ModelCore.EV8DSMS.getCreditRequest inValue = new ModelCore.EV8DSMS.getCreditRequest();
            inValue.Body = new ModelCore.EV8DSMS.getCreditRequestBody();
            inValue.Body.sessionKey = sessionKey;
            return ((ModelCore.EV8DSMS.SMSSoap)(this)).getCreditAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.every8d.com/API21/SOAP/SMS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.every8d.com/API21/SOAP/SMS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SMSSoap,
            
            SMSSoap12,
        }
    }
}
