//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.3928.0 自動產生。
// 
namespace ModelCore.Schema.EIVO {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class InvoiceRoot {
        
        private string companyBanField;
        
        private InvoiceRootInvoice[] invoiceField;
        
        private System.Nullable<short> notificationField;
        
        private bool notificationFieldSpecified;
        
        private string processTypeField;
        
        /// <remarks/>
        public string CompanyBan {
            get {
                return this.companyBanField;
            }
            set {
                this.companyBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CDS_Document")]
        public InvoiceRootInvoice[] Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotificationSpecified {
            get {
                return this.notificationFieldSpecified;
            }
            set {
                this.notificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ProcessType {
            get {
                return this.processTypeField;
            }
            set {
                this.processTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceRootInvoice {
        
        private System.Nullable<int> invoiceIDField;
        
        private string invoiceNumberField;
        
        private string invoiceDateField;
        
        private string invoiceTimeField;
        
        private string dataNumberField;
        
        private string dataDateField;
        
        private string googleIdField;
        
        private string sellerIdField;
        
        private string buyerNameField;
        
        private string buyerIdField;
        
        private System.Nullable<byte> buyerMarkField;
        
        private System.Nullable<byte> customsClearanceMarkField;
        
        private bool customsClearanceMarkFieldSpecified;
        
        private string invoiceTypeField;
        
        private string donateMarkField;
        
        private string carrierTypeField;
        
        private string carrierId1Field;
        
        private string carrierId2Field;
        
        private string printMarkField;
        
        private string nPOBANField;
        
        private string randomNumberField;
        
        private InvoiceRootInvoiceInvoiceItem[] invoiceItemField;
        
        private decimal salesAmountField;
        
        private System.Nullable<decimal> freeTaxSalesAmountField;
        
        private bool freeTaxSalesAmountFieldSpecified;
        
        private System.Nullable<decimal> zeroTaxSalesAmountField;
        
        private bool zeroTaxSalesAmountFieldSpecified;
        
        private byte taxTypeField;
        
        private decimal taxRateField;
        
        private bool taxRateFieldSpecified;
        
        private decimal taxAmountField;
        
        private decimal totalAmountField;
        
        private string currencyField;
        
        private decimal discountAmountField;
        
        private bool discountAmountFieldSpecified;
        
        private string customerIDField;
        
        private string dataSequenceNoField;
        
        private string contactNameField;
        
        private string eMailField;
        
        private string addressField;
        
        private string phoneField;
        
        private string mainRemarkField;
        
        private InvoiceRootInvoiceContact contactField;
        
        private InvoiceRootInvoiceCustomerDefined customerDefinedField;
        
        private System.Nullable<int> lineNoField;
        
        private bool lineNoFieldSpecified;
        
        private System.Nullable<byte> bondedAreaConfirmField;
        
        private string zeroTaxRateReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceTime {
            get {
                return this.invoiceTimeField;
            }
            set {
                this.invoiceTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNumber {
            get {
                return this.dataNumberField;
            }
            set {
                this.dataNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DataDate {
            get {
                return this.dataDateField;
            }
            set {
                this.dataDateField = value;
            }
        }
        
        /// <remarks/>
        public string GoogleId {
            get {
                return this.googleIdField;
            }
            set {
                this.googleIdField = value;
            }
        }
        
        /// <remarks/>
        public string SellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
            }
        }
        
        /// <remarks/>
        public string BuyerName {
            get {
                return this.buyerNameField;
            }
            set {
                this.buyerNameField = value;
            }
        }
        
        /// <remarks/>
        public string BuyerId {
            get {
                return this.buyerIdField;
            }
            set {
                this.buyerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> BuyerMark {
            get {
                return this.buyerMarkField;
            }
            set {
                this.buyerMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> CustomsClearanceMark {
            get {
                return this.customsClearanceMarkField;
            }
            set {
                this.customsClearanceMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomsClearanceMarkSpecified {
            get {
                return this.customsClearanceMarkFieldSpecified;
            }
            set {
                this.customsClearanceMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DonateMark {
            get {
                return this.donateMarkField;
            }
            set {
                this.donateMarkField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierType {
            get {
                return this.carrierTypeField;
            }
            set {
                this.carrierTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierId1 {
            get {
                return this.carrierId1Field;
            }
            set {
                this.carrierId1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierId2 {
            get {
                return this.carrierId2Field;
            }
            set {
                this.carrierId2Field = value;
            }
        }
        
        /// <remarks/>
        public string PrintMark {
            get {
                return this.printMarkField;
            }
            set {
                this.printMarkField = value;
            }
        }
        
        /// <remarks/>
        public string NPOBAN {
            get {
                return this.nPOBANField;
            }
            set {
                this.nPOBANField = value;
            }
        }
        
        /// <remarks/>
        public string RandomNumber {
            get {
                return this.randomNumberField;
            }
            set {
                this.randomNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceItem")]
        public InvoiceRootInvoiceInvoiceItem[] InvoiceItem {
            get {
                return this.invoiceItemField;
            }
            set {
                this.invoiceItemField = value;
            }
        }
        
        /// <remarks/>
        public decimal SalesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FreeTaxSalesAmount {
            get {
                return this.freeTaxSalesAmountField;
            }
            set {
                this.freeTaxSalesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FreeTaxSalesAmountSpecified {
            get {
                return this.freeTaxSalesAmountFieldSpecified;
            }
            set {
                this.freeTaxSalesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ZeroTaxSalesAmount {
            get {
                return this.zeroTaxSalesAmountField;
            }
            set {
                this.zeroTaxSalesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZeroTaxSalesAmountSpecified {
            get {
                return this.zeroTaxSalesAmountFieldSpecified;
            }
            set {
                this.zeroTaxSalesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxRateSpecified {
            get {
                return this.taxRateFieldSpecified;
            }
            set {
                this.taxRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountAmountSpecified {
            get {
                return this.discountAmountFieldSpecified;
            }
            set {
                this.discountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DataSequenceNo {
            get {
                return this.dataSequenceNoField;
            }
            set {
                this.dataSequenceNoField = value;
            }
        }
        
        /// <remarks/>
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string MainRemark {
            get {
                return this.mainRemarkField;
            }
            set {
                this.mainRemarkField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceRootInvoiceContact Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceRootInvoiceCustomerDefined CustomerDefined {
            get {
                return this.customerDefinedField;
            }
            set {
                this.customerDefinedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineNoSpecified {
            get {
                return this.lineNoFieldSpecified;
            }
            set {
                this.lineNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> BondedAreaConfirm {
            get {
                return this.bondedAreaConfirmField;
            }
            set {
                this.bondedAreaConfirmField = value;
            }
        }
        
        /// <remarks/>
        public string ZeroTaxRateReason {
            get {
                return this.zeroTaxRateReasonField;
            }
            set {
                this.zeroTaxRateReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceRootInvoiceInvoiceItem {
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private string unitField;
        
        private decimal unitPriceField;
        
        private decimal amountField;
        
        private short sequenceNumberField;
        
        private string itemField;
        
        private string remarkField;
        
        private System.Nullable<byte> taxTypeField;
        
        private bool taxTypeFieldSpecified;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public short SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxTypeSpecified {
            get {
                return this.taxTypeFieldSpecified;
            }
            set {
                this.taxTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceRootInvoiceContact {
        
        private string nameField;
        
        private string addressField;
        
        private string tELField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string TEL {
            get {
                return this.tELField;
            }
            set {
                this.tELField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceRootInvoiceCustomerDefined {
        
        private string projectNoField;
        
        private string purchaseNoField;
        
        private System.Nullable<short> stampDutyFlagField;
        
        private bool stampDutyFlagFieldSpecified;
        
        private InvoiceRootInvoiceCustomerDefinedPayment[] paymentField;
        
        /// <remarks/>
        public string ProjectNo {
            get {
                return this.projectNoField;
            }
            set {
                this.projectNoField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseNo {
            get {
                return this.purchaseNoField;
            }
            set {
                this.purchaseNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> StampDutyFlag {
            get {
                return this.stampDutyFlagField;
            }
            set {
                this.stampDutyFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StampDutyFlagSpecified {
            get {
                return this.stampDutyFlagFieldSpecified;
            }
            set {
                this.stampDutyFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Payment")]
        public InvoiceRootInvoiceCustomerDefinedPayment[] Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceRootInvoiceCustomerDefinedPayment {
        
        private string methodField;
        
        private decimal amountField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
}
