<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ModelCore</RootNamespace>
    <AssemblyName>ModelExtension</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib.Core\CommonLib.Core.csproj" />
    <ProjectReference Include="..\CommonLib.Logger\CommonLib.Logger.csproj" />
    <ProjectReference Include="..\CommonLib.PlugInAdapter\CommonLib.PlugInAdapter.csproj" />
    <ProjectReference Include="..\CommonLib.Utility\CommonLib.Utility.csproj" />
    <ProjectReference Include="..\ModelCore.EF\ModelCore.EF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MessagingToolkit.QRCode">
      <HintPath>..\WebHome\bin\Dependencies\Lib\MessagingToolkit.QRCode.dll</HintPath>
    </Reference>
    <Reference Include="QREncrypter">
      <HintPath>..\WebHome\bin\Dependencies\Lib\QREncrypter.dll</HintPath>
    </Reference>
    <Reference Include="ThoughtWorks.QRCode">
      <HintPath>..\WebHome\bin\Dependencies\Lib\ThoughtWorks.QRCode.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{3259aa49-8aa1-44d3-9025-a0b520596a8c}" />
  </ItemGroup>

</Project>
