//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace ModelCore.Schema.TurnKey.A1401 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1", IsNullable=false)]
    public partial class Invoice {
        
        /// <remarks/>
        public Main Main;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductItem", IsNullable=false)]
        public DetailsProductItem[] Details;
        
        /// <remarks/>
        public Amount Amount;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public partial class Main {
        
        /// <remarks/>
        public string InvoiceNumber;
        
        /// <remarks/>
        public string InvoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime InvoiceTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceTimeSpecified;
        
        /// <remarks/>
        public MainSeller Seller;
        
        /// <remarks/>
        public MainBuyer Buyer;
        
        /// <remarks/>
        public string CheckNumber;
        
        /// <remarks/>
        public BuyerRemarkEnum BuyerRemark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuyerRemarkSpecified;
        
        /// <remarks/>
        public string MainRemark;
        
        /// <remarks/>
        public CustomsClearanceMarkEnum CustomsClearanceMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomsClearanceMarkSpecified;
        
        /// <remarks/>
        public string TaxCenter;
        
        /// <remarks/>
        public string PermitDate;
        
        /// <remarks/>
        public string PermitWord;
        
        /// <remarks/>
        public string PermitNumber;
        
        /// <remarks/>
        public string Category;
        
        /// <remarks/>
        public string RelateNumber;
        
        /// <remarks/>
        public InvoiceTypeEnum InvoiceType;
        
        /// <remarks/>
        public string GroupMark;
        
        /// <remarks/>
        public DonateMarkEnum DonateMark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public partial class MainSeller {
        
        /// <remarks/>
        public string Identifier;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string PersonInCharge;
        
        /// <remarks/>
        public string TelephoneNumber;
        
        /// <remarks/>
        public string FacsimileNumber;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string CustomerNumber;
        
        /// <remarks/>
        public string RoleRemark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public partial class Amount {
        
        /// <remarks/>
        public long SalesAmount;
        
        /// <remarks/>
        public TaxTypeEnum TaxType;
        
        /// <remarks/>
        public decimal TaxRate;
        
        /// <remarks/>
        public long TaxAmount;
        
        /// <remarks/>
        public long TotalAmount;
        
        /// <remarks/>
        public long DiscountAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountAmountSpecified;
        
        /// <remarks/>
        public decimal OriginalCurrencyAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OriginalCurrencyAmountSpecified;
        
        /// <remarks/>
        public decimal ExchangeRate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExchangeRateSpecified;
        
        /// <remarks/>
        public CurrencyCodeEnum Currency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum TaxTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1 = 1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9 = 9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum CurrencyCodeEnum
    {

        TWD = 0,
        ADP,
        AED,
        AFA,
        ALL,
        AMD,
        ANG,
        AOA,
        AON,
        AOR,
        ARS,
        ATS,
        AUD,
        AWG,
        AZM,
        BAM,
        BBD,
        BDT,
        BEF,
        BGL,
        BGN,
        BHD,
        BIF,
        BMD,
        BND,
        BOB,
        BOV,
        BRL,
        BSD,
        BTN,
        BWP,
        BYB,
        BYR,
        BZD,
        CAD,
        CDF,
        CHF,
        CLF,
        CLP,
        CNY,
        COP,
        CRC,
        CUP,
        CVE,
        CYP,
        CZK,
        DEM,
        DJF,
        DKK,
        DOP,
        DZD,
        ECS,
        ECV,
        EEK,
        EGP,
        ERN,
        ESP,
        ETB,
        EUR,
        FIM,
        FJD,
        FKP,
        FRF,
        GBP,
        GEL,
        GHC,
        GIP,
        GMD,
        GNF,
        GRD,
        GTQ,
        GWP,
        GYD,
        HKD,
        HNL,
        HRK,
        HTG,
        HUF,
        IDR,
        IEP,
        ILS,
        INR,
        IQD,
        IRR,
        ISK,
        ITL,
        JMD,
        JOD,
        JPY,
        KES,
        KGS,
        KHR,
        KMF,
        KPW,
        KRW,
        KWD,
        KYD,
        KZT,
        LAK,
        LBP,
        LKR,
        LRD,
        LSL,
        LTL,
        LUF,
        LVL,
        LYD,
        MAD,
        MDL,
        MGF,
        MKD,
        MMK,
        MNT,
        MOP,
        MRO,
        MTL,
        MUR,
        MVR,
        MWK,
        MXN,
        MXV,
        MYR,
        MZM,
        NAD,
        NGN,
        NIO,
        NLG,
        NOK,
        NPR,
        NZD,
        OMR,
        PAB,
        PEN,
        PGK,
        PHP,
        PKR,
        PLN,
        PTE,
        PYG,
        QAR,
        ROL,
        RUB,
        RUR,
        RWF,
        SAR,
        SBD,
        SCR,
        SDD,
        SDP,
        SEK,
        SGD,
        SHP,
        SIT,
        SKK,
        SLL,
        SOS,
        SRG,
        STD,
        SVC,
        SYP,
        SZL,
        THB,
        TJR,
        TMM,
        TND,
        TOP,
        TPE,
        TRL,
        TTD,
        TZS,
        UAH,
        UGX,
        USD,
        USN,
        UYU,
        UZS,
        VEB,
        VND,
        VUV,
        WST,
        XAF,
        XAG,
        XAU,
        XBA,
        XBB,
        XBC,
        XBD,
        XCD,
        XDR,
        XEU,
        XFO,
        XFU,
        XOF,
        XPD,
        XPF,
        XPT,
        XXX,
        YER,
        YUM,
        ZAR,
        ZMK,
        ZRN,
        ZWD,
        VEF,
        AFN,
        AZN,
        GGP,
        GHS,
        IMP,
        JEP,
        MGA,
        MZN,
        RON,
        RSD,
        SDG,
        SPL,
        SRD,
        TJS,
        TRY,
        TVD
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public partial class MainBuyer {
        
        /// <remarks/>
        public string Identifier;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string PersonInCharge;
        
        /// <remarks/>
        public string TelephoneNumber;
        
        /// <remarks/>
        public string FacsimileNumber;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string CustomerNumber;
        
        /// <remarks/>
        public string RoleRemark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum BuyerRemarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1 = 1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum CustomsClearanceMarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1 = 1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum InvoiceTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01 = 1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public enum DonateMarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:A1401:3.1")]
    public partial class DetailsProductItem {
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public decimal Quantity;
        
        /// <remarks/>
        public decimal Quantity2;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        public string Unit2;
        
        /// <remarks/>
        public decimal UnitPrice;
        
        /// <remarks/>
        public decimal UnitPrice2;
        
        /// <remarks/>
        public decimal Amount;
        
        /// <remarks/>
        public decimal Amount2;
        
        /// <remarks/>
        public string SequenceNumber;
        
        /// <remarks/>
        public string Remark;
        
        /// <remarks/>
        public string RelateNumber;
    }
}
