//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.3928.0 自動產生。
// 
namespace ModelCore.Schema.TurnKey.E0504 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:E0504:4.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:GEINV:eInvoiceMessage:E0504:4.0", IsNullable=false)]
    public partial class Award {
        
        /// <remarks/>
        public Main Main;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PrizeInvoice", IsNullable=false)]
        public DetailsPrizeInvoice[] Details;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:E0504:4.0")]
    public partial class Main {
        
        /// <remarks/>
        public string HeadBan;
        
        /// <remarks/>
        public string YearMonth;
        
        /// <remarks/>
        public string AwardListType;
        
        /// <remarks/>
        public decimal TotalRecordCnt;
        
        /// <remarks/>
        public decimal TotalPrizeAmount;
        
        /// <remarks/>
        public string RecAwardBegin;
        
        /// <remarks/>
        public string RecAwardEnd;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:E0504:4.0")]
    public partial class DetailsPrizeInvoice {
        
        /// <remarks/>
        public string InvTrack;
        
        /// <remarks/>
        public string InvoiceNumber;
        
        /// <remarks/>
        public string InvoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime InvoiceTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceTimeSpecified;
        
        /// <remarks/>
        public DetailsPrizeInvoiceSeller Seller;
        
        /// <remarks/>
        public string BuyerId;
        
        /// <remarks/>
        public decimal TotalAmount;
        
        /// <remarks/>
        public string CarrierType;
        
        /// <remarks/>
        public string CarrierTypeName;
        
        /// <remarks/>
        public string CarrierId1;
        
        /// <remarks/>
        public string CarrierId2;
        
        /// <remarks/>
        public string RandomNumber;
        
        /// <remarks/>
        public string PrizeType;
        
        /// <remarks/>
        public decimal PrizeAmount;
        
        /// <remarks/>
        public string DepositMark;
        
        /// <remarks/>
        public string RedeemDataType;
        
        /// <remarks/>
        public string PrizeDataSource;
        
        /// <remarks/>
        public string PrintType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:E0504:4.0")]
    public partial class DetailsPrizeInvoiceSeller {
        
        /// <remarks/>
        public string Identifier;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string PersonInCharge;
        
        /// <remarks/>
        public string TelephoneNumber;
        
        /// <remarks/>
        public string FacsimileNumber;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string CustomerNumber;
        
        /// <remarks/>
        public string RoleRemark;
    }
}
