<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib.Core\CommonLib.Core.csproj" />
    <ProjectReference Include="..\CommonLib.Logger\CommonLib.Logger.csproj" />
    <ProjectReference Include="..\CommonLib.PlugInAdapter\CommonLib.PlugInAdapter.csproj" />
    <ProjectReference Include="..\CommonLib.Utility\CommonLib.Utility.csproj" />
    <ProjectReference Include="..\ModelCore.EF\ModelCore.EF.csproj" />
    <ProjectReference Include="..\ModelExtension.EF\ModelExtension.EF.csproj" />
  </ItemGroup>

</Project>
